# Generated by Django 3.1.7 on 2023-06-17 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='athletic_experience',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='expiration_date',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(default='Male', max_length=6),
        ),
    ]
