# Generated by Django 3.1.7 on 2023-06-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_auto_20230617_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(default='20'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='00000000000', max_length=11),
        ),
        migrations.AddField(
            model_name='user',
            name='registration_date',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
