# Generated by Django 4.2.2 on 2023-06-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("member", "0006_auto_20230617_2120"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female")],
                default="Male",
                max_length=6,
            ),
        ),
    ]
