# Generated by Django 4.2.2 on 2023-06-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Workout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("member_id", models.CharField(max_length=4)),
                ("date", models.DateField()),
                ("workout", models.CharField(max_length=20)),
                ("num_of_sets", models.IntegerField(default=5)),
                (
                    "reps",
                    models.JSONField(default='{"1": 0, "2":0, "3":0, "4":0, "5":0}'),
                ),
            ],
        ),
    ]
