# Generated by Django 4.2.2 on 2023-06-22 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workout",
            name="weights",
            field=models.JSONField(default='{"1": 0, "2":0, "3":0, "4":0, "5":0}'),
        ),
    ]
