# Generated by Django 4.2.2 on 2023-06-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0002_workout_weights"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workout",
            name="reps",
        ),
        migrations.RemoveField(
            model_name="workout",
            name="weights",
        ),
        migrations.AddField(
            model_name="workout",
            name="reps_list",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="workout",
            name="weight_list",
            field=models.CharField(default="", max_length=200),
        ),
    ]
