# Generated by Django 4.2.2 on 2023-06-21 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("member_id", models.CharField(max_length=4)),
                ("date", models.DateField()),
                ("check_in_time", models.TimeField()),
                ("check_out_time", models.TimeField()),
                ("workout_duration", models.CharField(max_length=3)),
            ],
        ),
    ]
