# Generated by Django 4.2.2 on 2023-06-24 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_alter_attendance_workout_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="check_out_time",
            field=models.TimeField(default=None),
        ),
    ]
