# Generated by Django 4.2.2 on 2023-06-24 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0003_alter_attendance_check_out_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="check_out_time",
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="workout_duration",
            field=models.IntegerField(max_length=2, null=True),
        ),
    ]
