# Generated by Django 4.2.2 on 2023-06-24 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0004_alter_attendance_check_out_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="check_out_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="workout_duration",
            field=models.IntegerField(blank=True, max_length=2, null=True),
        ),
    ]
