# Generated by Django 4.2.2 on 2023-06-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0005_alter_attendance_check_out_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="workout_duration",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
